# Geyser Configuration File

# Bedrock client connection settings
bedrock:
  # The IP address that will listen for connections.
  # Generally, you should only uncomment and change this if you want to limit what IPs can connect to your server.
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
  # Some hosting services change your Java port everytime you start the server and require the same port to be used for Bedrock.
  # This option makes the Bedrock port the same as the Java port every time you start the server.
  # This option is for the plugin version only.
  clone-remote-port: false
  # The MOTD that will be broadcasted to Minecraft: Bedrock Edition clients. This is irrelevant if "passthrough-motd" is set to true
  motd1: "MCHGLand Server"
  motd2: "Java & Bedrock Compatible!"
  # The Server Name that will be sent to Minecraft: Bedrock Edition clients. This is visible in the pause menu and settings.
  server-name: "MCHGLand"
  # How much to compress network traffic to the Bedrock client. The higher the number, the more CPU usage used, but
  # the smaller the bandwidth used. Does not have any effect below -1 or above 9. Set to -1 to disable.
  compression-level: 6
  # Whether to enable proxy protocol or not for clients. You DO NOT WANT this feature unless you run UDP proxy
  # in front of your Geyser instance.
  enable-proxy-protocol: false
  # A list of allowed proxy IPs if the above is enabled.
  proxy-protocol-whitelisted-ips: []

# Remote (Java Edition) server settings
remote:
  # The IP address of the remote (Java Edition) server
  address: 127.0.0.1
  # The port of the remote (Java Edition) server
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  # For plugin versions, it's recommended to keep the `address` as "auto" so Geyser doesn't try to connect to itself.
  auth-type: offline
  # Allow for password-based authentication methods through Geyser. Only useful in online mode.
  # If this is false, users must authenticate to Microsoft/Mojang through a browser to log in.
  allow-password-authentication: true
  # Whether to enable PROXY protocol or not while connecting to the server.
  # This is useful only when:
  # 1) Your server supports PROXY protocol (it probably doesn't)
  # 2) You run Geyser on a different machine than your server and want the original IP to be passed through.
  use-proxy-protocol: false
  # Forward the hostname that the Bedrock client used to connect over to the Java server. This is designed to be used for
  # forced hosts on proxies.
  forward-hostname: false

# Floodgate uses encryption to ensure use from authorised sources.
# This should point to the public key generated by Floodgate (Bungee or CraftBukkit)
# You can ignore this when not using Floodgate.
# If you're using a plugin version of Floodgate on the same server, the key will automatically be picked up from Floodgate.
floodgate:
  key-file: key.pem
  # Specify the username prefix for Floodgate players. It's recommended to keep the default dot (.) as it doesn't
  # conflict with other authentication methods (Xbox, PSN, etc.)
  username-prefix: "."
  # Specify if the usernames have spaces in them
  replace-spaces: true

# For online mode authentication type only. Stores a cache of placed blocks in a world file which is used to send only block changes.
# This is mostly useful for super flat worlds.
cache-chunks: true

# Specify the path to store identities and UUID info for Floodgate
userdata-folder: userdata

# Bedrock clients can have custom skins, capes and geometry.
# Bedrock skins and capes can be forwarded to the Java server using Floodgate or manually implementing the API.
# Allow custom skulls to be displayed. Keeping them will display the player's custom skin on their skull.
allow-custom-skulls: true

# Bedrock clients can have custom skins, including ones with transparent parts.
# These are more prone to abuse, so they are disabled by default - uncomment to enable them.
# allow-custom-skins: true

# Allow third party deadmau5 ears to be visible. Currently allowing:
# - Deadmau5 ears (including third party mods / texture packs)
# - Cat ears
allow-third-party-deadmau5ears: false

# Allow a fake cooldown indicator to be sent. Bedrock players otherwise have no indicator of a cooldown.
# This setting should only be disabled if cooldown-related plugins handle this themselves.
# This only works on Bedrock 1.19.10 and newer.
show-cooldown: title

# Controls if coordinates are shown to players.
show-coordinates: true

# The default locale if we dont have the one the client requested. Uncomment to not use the default system language.
default-locale: en_us

# Configures if chunk loading/sending should be handled by Geyser or the server.
# When set to true, Geyser will handle chunk loading/sending which may result in better performance.
# When set to false, the server will handle chunk loading/sending which may result in better mod compatibility.
cache-chunked-loading: true

# Whether to log player IP addresses when they connect.
log-player-ip-addresses: true

# Specify how many days images will be cached to disk to save downloading them from the internet.
# A value of 0 is disabled. (Default: 0)
cache-images: 0

# Specify the maximum number of custom skulls to cache.
max-cached-skins: 100

# Allow third party capes to be visible. Currently allowing:
# - OptiFine capes
# - LabyMod capes
# - 5Zig capes
allow-third-party-capes: true

# Allow third party ears to be visible. Currently allowing:
# - Deadmau5 ears (including third party mods / texture packs)
allow-third-party-ears: false

# Allow Bedrock players to use an axe like a sword. This should only be disabled if plugins handle this themselves.
add-non-bedrock-items: true

# Force clients to load all resource packs if there are any.
# If set to false, it allows the user to disconnect from the server if they don't
# want to download the resource packs.
force-resource-packs: true

# Allows Xbox achievements to be unlocked.
# This disables certain commands and features to prevent cheating.
xbox-achievements-enabled: false

# bStats is a stat collection service.
# All data that is sent is completely anonymous and is only used to show overall trends.
# To learn what information is collected, please see https://bstats.org/privacy-policy
# https://bstats.org/plugin/server-implementation/GeyserMC
metrics:
  # If metrics should be enabled
  enabled: true
  # UUID of server, don't change!
  uuid: 94062a76-a717-4c3a-bfcd-a6b7445a5856

# ADVANCED OPTIONS - DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING!

# Geyser updates the Scoreboard after every Scoreboard packet, but when there are a lot of scoreboard packets per second,
# this can cause serious lag. This option allows you to specify after how many Scoreboard packets per seconds
# the Scoreboard updates will be limited to four updates per second.
scoreboard-packet-threshold: 20

# Allow connections from ProxyPass and Waterdog.
# See https://www.spigotmc.org/wiki/firewall-guide/ for assistance - use UDP instead of TCP.
enable-proxy-connections: false

# The IP address to bind the query port to.
# This is the same as the bedrock IP address.
query-port: 19132

# The port to bind the query port to.
# This is the same as the bedrock port.
query-enabled: false

# The MOTD that will be broadcasted to Minecraft: Bedrock Edition clients. This is irrelevant if "passthrough-motd" is set to true
# If either of these are empty, either the respective server.properties MOTD or a default Geyser MOTD will be used
passthrough-motd: false

# The Server Name that will be sent to Minecraft: Bedrock Edition clients. This is visible in the pause menu and settings.
passthrough-protocol-name: false

# Ignore the server properties file and use the default Geyser MOTD and Server Name.
# This is useful if you want to use a custom MOTD and Server Name for Bedrock clients.
ignore-server-properties: false

# The maximum number of players that can connect to the server.
# This is only used if the server is in online mode.
max-players: 100

# If debug mode is enabled, all packets will be logged to the console.
debug-mode: false

# If set to true, the server will not check for updates.
disable-server-update-checks: false

# The compression level to use for network traffic.
# -1 to disable compression.
# 0-9 to set the compression level.
compression-level: 6

# The number of threads to use for network I/O.
# This should be set to the number of CPU cores on your server.
# If you're not sure, leave this at the default value.
netty-threads: 4

# Configuration version - do not change!
config-version: 4
